---
settings:
  name: BlueXP ransomware protection
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documenti sulla protezione ransomware BlueXP
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità della protezione dal ransomware BlueXP
      url: "/whats-new.html"
  - title: Inizia subito
    entries:
    - title: Scopri di più sulla protezione ransomware di BlueXP
      url: "/concept-ransomware-protection.html"
    - title: Prerequisiti
      url: "/rp-start-prerequisites.html"
    - title: Avvio rapido
      url: "/rp-start-quick-start.html"
    - title: Imposta la protezione dal ransomware BlueXP
      url: "/rp-start-setup.html"
    - title: Accedi alla protezione dal ransomware di BlueXP
      url: "/rp-start-login.html"
    - title: Impostare la licenza
      url: "/rp-start-licenses.html"
    - title: Rileva i carichi di lavoro
      url: "/rp-start-discover.html"
    - title: Configurare le destinazioni di backup e abilitare il rilevamento delle
        minacce
      url: "/rp-use-settings.html"
    - title: FAQ
      url: "/rp-start-faq.html"
  - title: Utilizzare la protezione ransomware BlueXP
    entries:
    - title: USA una panoramica sulla protezione dal ransomware di BlueXP
      url: "/rp-use-overview.html"
    - title: Visualizza la salute del carico di lavoro utilizzando la Dashboard
      url: "/rp-use-dashboard.html"
    - title: Proteggere i carichi di lavoro
      entries:
      - title: Proteggi i carichi di lavoro con strategie di protezione dal ransomware
        url: "/rp-use-protect.html"
      - title: Eseguire la scansione dei dati personali identificabili
        url: "/rp-use-protect-classify.html"
    - title: Rispondere a un avviso rilevato
      url: "/rp-use-alert.html"
    - title: Ripristino da un attacco ransomware
      url: "/rp-use-recover.html"
    - title: Scarica i report
      url: "/rp-use-reports.html"
  - section: support
  - title: Riferimento
    entries:
    - title: Privileges per il controllo degli accessi in base al ruolo
      url: "/rp-reference-roles.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
