---
sidebar: sidebar 
permalink: rp-reference-roles.html 
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account 
summary: 'La protezione ransomware BlueXP  utilizza il role-based access control (RBAC) per gestire l"accesso a funzionalità e azioni specifiche di ciascun utente. Il servizio utilizza ruoli specifici per la protezione dal ransomware BlueXP  (RPS).' 
---
= Accesso alle funzionalità della protezione ransomware BlueXP  in base al ruolo
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La protezione ransomware BlueXP  impiega ruoli per gestire l'accesso che ogni utente ha a caratteristiche e azioni specifiche.

Il servizio utilizza i ruoli seguenti, specifici per la protezione ransomware BlueXP .

* *Amministratore della protezione ransomware*: Consente di gestire le azioni nelle schede Protect, Alerts, Recover, Settings e Reports.
* *Visualizzatore protezione ransomware*: Consente di visualizzare i dati del carico di lavoro, visualizzare i dati degli avvisi, scaricare i dati di recupero e scaricare i report.


La piattaforma BlueXP  per tutti i servizi BlueXP  utilizza i seguenti tipi di ruoli:

* *I ruoli della piattaforma* consentono di gestire gli utenti, assegnarli alle risorse e assegnare loro ruoli insieme ad altre azioni a livello di piattaforma.
* *I ruoli dei servizi dati* sono limitati solo a un servizio dati specifico. È possibile disporre di diversi ruoli per i servizi dati in base al proprio lavoro. La protezione ransomware BlueXP  è uno dei servizi dati di BlueXP .


Altri ruoli delle piattaforme BlueXP  sono considerati spettatori nella protezione dal ransomware di BlueXP . Ad esempio, il ruolo *Visualizzatore protezione ransomware* consente di visualizzare i piani di protezione, ma non di eseguire alcuna azione nella protezione ransomware BlueXP.

Per informazioni dettagliate su tutti i ruoli della piattaforma BlueXP , vedere https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["La documentazione di installazione e amministrazione di BlueXP "^].

La tabella seguente indica le azioni eseguibili da ogni ruolo di protezione ransomware BlueXP .

[cols="40,20a,20a"]
|===
| Funzione e azione | Amministratore della protezione dal ransomware | Visualizzatore di protezione dal ransomware 


| Visualizza dashboard e tutte le schede  a| 
Sì
 a| 
Sì



| Sul dashboard, aggiornare lo stato del suggerimento  a| 
Sì
 a| 
No



| Inizia la prova gratuita  a| 
Sì
 a| 
No



| Avvia il rilevamento dei carichi di lavoro  a| 
Sì
 a| 
No



| Avvia il rilevamento dei carichi di lavoro  a| 
Sì
 a| 
No



3+| *Nella scheda protezione*: 


| Aggiungere, modificare o eliminare i piani di protezione  a| 
Sì
 a| 
No



| Proteggere i carichi di lavoro  a| 
Sì
 a| 
No



| Identificazione dell'esposizione ai dati sensibili  a| 
Sì
 a| 
No



| Elencare i piani di protezione e i dettagli  a| 
Sì
 a| 
Sì



| Elencare i gruppi di protezione  a| 
Sì
 a| 
Sì



| Visualizzare i dettagli del gruppo di protezione  a| 
Sì
 a| 
Sì



| Creare, modificare o eliminare un gruppo di protezione  a| 
Sì
 a| 
No



| Scaricare i dati  a| 
Sì
 a| 
Sì



3+| *Nella scheda Avvisi*: 


| Visualizzare gli avvisi e i dettagli degli avvisi  a| 
Sì
 a| 
Sì



| Modifica stato incidente  a| 
Sì
 a| 
No



| Contrassegnare un avviso per il ripristino  a| 
Sì
 a| 
No



| Visualizzare i dettagli dell'incidente  a| 
Sì
 a| 
Sì



| Respingere o risolvere gli incidenti  a| 
Sì
 a| 
No



| Blocca utente  a| 
Sì
 a| 
No



| Ottieni l'elenco completo dei file interessati  a| 
Sì
 a| 
No



| Scarica i dati degli avvisi  a| 
Sì
 a| 
Sì



3+| *Nella scheda Recupera*: 


| Scaricare i file interessati  a| 
Sì
 a| 
No



| Ripristina il workload  a| 
Sì
 a| 
No



| Scaricare i dati di ripristino  a| 
Sì
 a| 
Sì



| Scarica i report  a| 
Sì
 a| 
Sì



3+| *Nella scheda Impostazioni*: 


| Aggiungere o modificare le destinazioni di backup  a| 
Sì
 a| 
No



| Elencare le destinazioni di backup  a| 
Sì
 a| 
Sì



| Visualizza destinazioni SIEM connesse  a| 
Sì
 a| 
Sì



| Aggiungere o modificare target SIEM  a| 
Sì
 a| 
No



| Collegare gli obiettivi di sicurezza del carico di lavoro  a| 
Sì
 a| 
No



| Visualizzare lo stato della connessione di sicurezza del carico di lavoro  a| 
Sì
 a| 
Sì



| Scollegare le destinazioni di sicurezza del carico di lavoro  a| 
Sì
 a| 
No



| Configurare la preparazione  a| 
Sì
 a| 
No



| Avviare il drill-down  a| 
Sì
 a| 
No



| Reimpostare il trapano pronto  a| 
Sì
 a| 
No



| Modifica esercitazione di preparazione  a| 
Sì
 a| 
No



| Rivedere lo stato di preparazione  a| 
Sì
 a| 
Sì



| Aggiornare la configurazione del rilevamento  a| 
Sì
 a| 
No



| Visualizzare la configurazione del rilevamento  a| 
Sì
 a| 
Sì



3+| *Nella scheda rapporti*: 


| Scarica i report  a| 
Sì
 a| 
Sì

|===