---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: Queste FAQ possono essere utili se stai cercando una risposta rapida a una domanda. 
---
= Domande frequenti sulla protezione dal ransomware BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Queste FAQ possono essere utili se stai cercando una risposta rapida a una domanda.



== Accesso

*Qual è l'URL di protezione dal ransomware BlueXP?*
Per l'URL, in un browser, immettere: https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^] Per accedere alla console BlueXP.

*Ti serve una licenza per usare la protezione da ransomware di BlueXP?*
Non è richiesto un file di licenza NetApp (NLF). L'anteprima della protezione dal ransomware di BlueXP non richiede licenze speciali.  Tutte le licenze di anteprima sono licenze di valutazione.

La versione in anteprima di questo servizio richiede una licenza del servizio di backup e recovery di BlueXP.


TIP: Per la versione di anteprima, NetApp aiuta a configurare la valutazione e le eventuali licenze richieste.

*In che modo abiliti la protezione dal ransomware BlueXP?*
La protezione dal ransomware di BlueXP non richiede alcuna abilitazione. L'opzione di protezione dal ransomware viene automaticamente abilitata nel sistema di navigazione BlueXP a sinistra.

Per la versione di anteprima, devi iscriverti o contattare il tuo commerciale NetApp per provare questo servizio. Quindi, quando si utilizza il connettore BlueXP, esso includerà le funzionalità appropriate per il servizio.

**La protezione anti-ransomware BlueXP è disponibile in modalità standard, limitata e privata?**
Al momento, la protezione dal ransomware di BlueXP è disponibile solo in modalità standard. Continua a seguirci per saperne di più.

Per una spiegazione di queste modalità in tutti i servizi BlueXP, fare riferimento a. https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Modalità di implementazione di BlueXP"^].

**Come vengono gestite le autorizzazioni di accesso?**
Solo gli amministratori degli account possono avviare il servizio e rilevare i carichi di lavoro (perché questo implica impegnarsi all'utilizzo di una risorsa). Le interazioni successive possono essere effettuate da qualsiasi ruolo.

**Qual è la migliore risoluzione del dispositivo?**
La risoluzione consigliata del dispositivo per la protezione dal ransomware BlueXP è di 1920x1080 o superiore.

**Quale browser devo utilizzare?**
Qualsiasi browser moderno funzionerà.



== Interazione con altri servizi

*La protezione dal ransomware di BlueXP è a conoscenza delle impostazioni di protezione di NetApp ONTAP?*
Sì, la protezione dal ransomware BlueXP rileva le pianificazioni Snapshot impostate in ONTAP.

*Se imposti una policy utilizzando la protezione dal ransomware di BlueXP, devi apportare modifiche future solo in questo servizio?*
No, è possibile apportare modifiche ai criteri da qualsiasi servizio.



== Carichi di lavoro

**Che cosa costituisce un carico di lavoro?**
Un carico di lavoro include tutti i volumi utilizzati da una singola istanza dell'applicazione. Ad esempio, un'istanza di Oracle DB implementata in ora3.host.com può avere vol1 GB e vol2 GB rispettivamente per dati e registri. Questi volumi costituiscono insieme il carico di lavoro per quella specifica istanza dell'istanza del database Oracle.

*In che modo la protezione dal ransomware di BlueXP assegna la priorità ai dati del carico di lavoro?*
La priorità dei dati per la versione di anteprima è determinata dalle copie Snapshot effettuate e dai backup pianificati.

La priorità del carico di lavoro è determinata dalle seguenti frequenze di istantanea:

* *Critico*: Copie snapshot acquisite meno di 1 TB all'ora (pianificazione di protezione altamente aggressiva)
* *Importante*: Le copie snapshot sono state acquisite meno di 1 al giorno e più di 1 all'ora
* *Standard*: Le copie snapshot sono state acquisite più di 1 copie al giorno


**Aggiunto nuovo volume, ma non appare ancora**
Se è stato aggiunto un nuovo volume al proprio ambiente, ripetere il rilevamento e applicare criteri di protezione per proteggere il nuovo volume.

**La Dashboard non mostra tutti i miei workload. Che cosa potrebbe essere sbagliato?**
Al momento sono supportati solo volumi NFS. I volumi iSCSI, i volumi CIFS e altre configurazioni non supportate vengono filtrati e non vengono visualizzati sulla dashboard.



== Policy di protezione

*Le policy ransomware di BlueXP coesistono con altri tipi di policy dei workload?*
Al momento, il backup e recovery di BlueXP (Cloud Backup) supporta una policy di backup per ogni volume. Pertanto, il backup e recovery di BlueXP e la protezione dal ransomware di BlueXP condividono le policy di backup.

Le copie Snapshot non sono limitate e possono essere aggiunte separatamente da ciascun servizio.
