---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, aws, azure 
summary: Per utilizzare la protezione dal ransomware di BlueXP, esegui alcuni passaggi per configurarla. 
---
= Imposta la protezione dal ransomware BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Per utilizzare la protezione dal ransomware di BlueXP, esegui alcuni passaggi per configurarla.

Prima di iniziare, rivedere link:rp-start-prerequisites.html["prerequisiti"] per garantire che il tuo ambiente sia pronto.



== Preparare la destinazione di backup

Preparare una delle seguenti destinazioni di backup:

* NetApp StorageGRID
* Amazon Web Services
* Piattaforma Google Cloud
* Microsoft Azure


Dopo aver configurato le opzioni nella destinazione di backup stessa, la configurerai in seguito come destinazione di backup nel servizio di protezione dal ransomware di BlueXP. Per ulteriori informazioni su come configurare la destinazione di backup nella protezione ransomware BlueXP , fare riferimento a link:rp-use-settings.html["Configurare le destinazioni di backup"].



=== Preparare StorageGRID a diventare una destinazione di backup

Se si desidera utilizzare StorageGRID come destinazione di backup, fare riferimento alla sezione https://docs.netapp.com/us-en/storagegrid-117/index.html["Documentazione StorageGRID"^] Per ulteriori informazioni su StorageGRID.



=== Prepara AWS a diventare una destinazione di backup

* Configurare un account in AWS.
* Configurare https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Autorizzazioni AWS"^] In AWS.


Per informazioni sulla gestione dello storage AWS in BlueXP, fare riferimento a. https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-amazon-s3.html["Gestisci i bucket Amazon S3"^].



=== Preparare Azure a diventare una destinazione di backup

* Configurare un account in Azure.
* Configurare https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Autorizzazioni Azure"^] In Azure.


Per informazioni sulla gestione dello storage Azure in BlueXP, fare riferimento a. https://docs.netapp.com/us-en/bluexp-blob-storage/task-view-azure-blob-storage.html["Gestione degli account storage Azure"^].



== Configurare BlueXP

Il passo successivo è la configurazione di BlueXP e del servizio di protezione dal ransomware di BlueXP.

Revisione https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html["Requisiti BlueXP per la modalità standard"^].



=== Creare un connettore in BlueXP

Contattare il rappresentante di vendita NetApp per provare o utilizzare questo servizio. Quindi, quando usi il connettore BlueXP, includerai le funzionalità appropriate per il servizio di protezione dal ransomware.

Per creare un connettore in BlueXP prima di utilizzare il servizio, contattare l'amministratore dell'organizzazione BlueXP che dispone delle autorizzazioni per creare connettori e fare riferimento alla documentazione BlueXP che descrive  https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["Come creare un connettore BlueXP"^] .


NOTE: Se disponi di più connettori BlueXP, il servizio scansionerà i dati su tutti i connettori oltre a quello attualmente visualizzato nell'interfaccia utente di BlueXP. Questo servizio rileva tutti i progetti e tutti i connettori associati a questa organizzazione.
