---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: Queste FAQ possono essere utili se stai cercando una risposta rapida a una domanda. 
---
= Domande frequenti sulla protezione dal ransomware BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Queste FAQ possono essere utili se stai cercando una risposta rapida a una domanda.



== Accesso

*Qual è l'URL di protezione dal ransomware BlueXP?*
Per l'URL, in un browser, immettere: https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^] Per accedere alla console BlueXP.

*Ti serve una licenza per usare la protezione da ransomware di BlueXP?*

È possibile utilizzare i seguenti tipi di licenza:

* Iscriviti per una prova gratuita di 90 giorni.
* Acquista un abbonamento pay-as-you-go (PAYGO) con Amazon Web Services (AWS) Marketplace.
* BYOL (Bring Your Own License), ovvero un file di licenza NetApp (NLF) ottenuto dal rappresentante vendite NetApp Puoi utilizzare il numero di serie della licenza per attivare il BYOL nel Digital Wallet di BlueXP.


*In che modo abiliti la protezione dal ransomware BlueXP?*
La protezione dal ransomware di BlueXP non richiede alcuna abilitazione. L'opzione di protezione dal ransomware viene automaticamente abilitata nel sistema di navigazione BlueXP a sinistra.

Per iniziare, devi iscriverti o contattare il tuo rappresentante commerciale NetApp per provare questo servizio. Quindi, quando si utilizza il connettore BlueXP, esso includerà le funzionalità appropriate per il servizio.

**La protezione anti-ransomware BlueXP è disponibile in modalità standard, limitata e privata?**
Al momento, la protezione dal ransomware di BlueXP è disponibile solo in modalità standard. Continua a seguirci per saperne di più.

Per una spiegazione di queste modalità in tutti i servizi BlueXP, fare riferimento a. https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Modalità di implementazione di BlueXP"^].

**Come vengono gestite le autorizzazioni di accesso?**
Solo gli amministratori degli account possono avviare il servizio e rilevare i carichi di lavoro (perché questo implica impegnarsi all'utilizzo di una risorsa). Le interazioni successive possono essere effettuate da qualsiasi ruolo.

**Qual è la migliore risoluzione del dispositivo?**
La risoluzione consigliata del dispositivo per la protezione dal ransomware BlueXP è di 1920x1080 o superiore.

**Quale browser devo utilizzare?**
Qualsiasi browser moderno funzionerà.



== Interazione con altri servizi

*La protezione dal ransomware di BlueXP è a conoscenza delle impostazioni di protezione di NetApp ONTAP?*
Sì, la protezione dal ransomware BlueXP rileva le pianificazioni Snapshot impostate in ONTAP.

*Se imposti una policy utilizzando la protezione dal ransomware di BlueXP, devi apportare modifiche future solo in questo servizio?*
Ti consigliamo di apportare modifiche alla policy dal servizio di protezione dal ransomware di BlueXP.



== Carichi di lavoro

**Che cosa costituisce un carico di lavoro?**
Un carico di lavoro include tutti i volumi utilizzati da una singola istanza dell'applicazione. Ad esempio, un'istanza di Oracle DB implementata in ora3.host.com può avere vol1 GB e vol2 GB rispettivamente per dati e registri. Questi volumi costituiscono insieme il carico di lavoro per quella specifica istanza dell'istanza del database Oracle.

*In che modo la protezione dal ransomware di BlueXP assegna la priorità ai dati del carico di lavoro?*
La priorità dei dati è determinata dalle copie Snapshot create e dai backup pianificati.

La priorità del carico di lavoro è determinata dalle frequenze dell'istantanea.

link:rp-use-protect.html["Scopri la priorità o l'importanza del carico di lavoro"].

**Aggiunto nuovo volume, ma non appare ancora**
Se è stato aggiunto un nuovo volume al proprio ambiente, ripetere il rilevamento e applicare criteri di protezione per proteggere il nuovo volume.

**La Dashboard non mostra tutti i miei workload. Che cosa potrebbe essere sbagliato?**
Al momento sono supportati solo volumi NFS e CIFS. I volumi iSCSI e altre configurazioni non supportate vengono filtrati e non vengono visualizzati nella dashboard.



== Policy di protezione

*Le policy ransomware di BlueXP coesistono con altri tipi di policy dei workload?*
Al momento, il backup e recovery di BlueXP (Cloud Backup) supporta una policy di backup per ogni volume. Pertanto, il backup e recovery di BlueXP e la protezione dal ransomware di BlueXP condividono le policy di backup.

Le copie Snapshot non sono limitate e possono essere aggiunte separatamente da ciascun servizio.
