---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: what are bluexp ransomware protection requirements, bluexp ransomware protection, ransomware protection prerequisites 
summary: 'Inizia a usare la protezione dal ransomware di BlueXP verificando il supporto per il tuo ambiente, l"accesso alla rete, i dati di accesso e il browser web.' 
---
= Prerequisiti della protezione dal ransomware di BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
Inizia subito con la protezione dal ransomware di BlueXP verificando la preparazione del tuo ambiente operativo, dell'accesso, dell'accesso alla rete e del browser web.

Per utilizzare la protezione dal ransomware BlueXP, hai bisogno di questi prerequisiti:

* Un account in NetApp StorageGRID o AWS S3 per le destinazioni di backup e il set di autorizzazioni di accesso
+
Fare riferimento a. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Elenco delle autorizzazioni AWS"^] per ulteriori informazioni.

* ONTAP 9.11.1 e versioni successive
+
** Autorizzazioni ONTAP di amministrazione cluster
** Una licenza per la protezione autonoma da ransomware NetApp, utilizzata dalla protezione BlueXP, abilitata sull'istanza ONTAP on-premise, a seconda della versione di ONTAP che stai utilizzando. Fare riferimento a. https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Panoramica della protezione ransomware autonoma"^].
+

NOTE: La release generale della protezione ransomware di BlueXP, a differenza della release Preview, include una licenza per la tecnologia di protezione autonoma dal ransomware NetApp. Fare riferimento a. https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Panoramica della protezione ransomware autonoma"^] per ulteriori informazioni.

+
Per ulteriori informazioni sulle licenze, fare riferimento a. link:concept-ransomware-protection.html["Scopri di più sulla protezione ransomware di BlueXP"].



* In BlueXP:
+
** Un ambiente di lavoro BlueXP con storage on-premise NetApp (con protocolli NAS o CIFS)
** Configurare un connettore BlueXP per ogni cloud privato virtuale (VPC) o in un'area on-premise in BlueXP. Fare riferimento a. https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["Documentazione di BlueXP per configurare il connettore"^].
+

NOTE: Se disponi di più connettori BlueXP, il servizio scansionerà i dati su tutti i connettori oltre a quello attualmente visualizzato nell'interfaccia utente di BlueXP.

** Un account BlueXP con almeno un connettore attivo che si connette ai cluster ONTAP on-premise. Tutti gli ambienti di origine e lavoro devono trovarsi sullo stesso account BlueXP.
** Un account utente BlueXP con privilegi di account Admin per rilevare le risorse
** Un ambiente di lavoro BlueXP con storage on-premise NetApp (con protocolli NAS o CIFS)
** https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Requisiti standard di BlueXP"^]





NOTE: Il servizio di backup e recovery di BlueXP non deve più essere già abilitato nell'ambiente di lavoro. Il servizio di protezione dal ransomware di BlueXP aiuta a configurare una destinazione di backup tramite l'opzione Settings. Vedere link:rp-use-settings.html["Configurare le impostazioni"].
