---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, ransomware protection' 
summary: Scopri le novità di BlueXP ransomware Protection. 
---
= Novità della protezione ransomware di BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le novità di BlueXP ransomware Protection.



== 3 aprile 2023



=== Nuove azioni consigliate per proteggere i dati da attacchi ransomware

* Una nuova azione consigliata per il backup dei file business-critical nelle origini dati identifica come proteggere le categorie di dati più importanti eseguendo il backup dei volumi utilizzando il backup e il ripristino BlueXP. Ciò è importante nel caso in cui sia necessario ripristinare i dati a causa di un attacco ransomware. Il consiglio reindirizza l'utente all'interfaccia di backup e ripristino di BlueXP in modo da poter attivare il backup sui volumi necessari.
* Una nuova azione consigliata per "attivare le configurazioni di cyberstorage per le origini dati" identifica se le funzionalità Six ONTAP che aiutano a proteggere i dati sono attivate o disattivate. È necessario abilitare queste funzionalità su tutti i sistemi ONTAP e Cloud Volumes ONTAP on-premise.


https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#list-of-recommended-actions["Consulta l'elenco di tutte le azioni consigliate"].



== 7 marzo 2023



=== È stata aggiunta una nuova dashboard di ripristino ransomware per aiutare a ripristinare il sistema da un attacco

La dashboard di ripristino ransomware offre opzioni per il ripristino dei dati che potrebbero essere stati infettati dal ransomware. In questo modo è possibile eseguire il backup e l'esecuzione dei sistemi in modo molto rapido. A questo punto, l'azione di ripristino consente di sostituire un volume corrotto con una copia Snapshot che non è stata interessata dal ransomware. https://docs.netapp.com/us-en/cloud-manager-ransomware/task-ransomware-recovery.html["Scopri di più"].



== 5 febbraio 2023



=== Possibilità di definire le policy che identificano i dati che si considerano business-critical

Una nuova pagina per i dati business-critical è stata aggiunta alla protezione ransomware di BlueXP. Questa pagina consente di visualizzare tutti i criteri definiti nella classificazione BlueXP. Puoi selezionare le policy che identificano i dati critici per la tua azienda in modo che la dashboard di protezione ransomware di BlueXP e altri pannelli ransomware riflettano i potenziali problemi in base ai dati più importanti.

Se non è stata attivata una di queste policy per il servizio di protezione ransomware BlueXP, nel pannello delle azioni consigliate viene visualizzata una nuova azione denominata "Configura i dati business-critical".

https://docs.netapp.com/us-en/cloud-manager-ransomware/task-select-business-critical-policies.html["Scopri di più sulla pagina dati business-critical"^].



=== La protezione ransomware di BlueXP è passata dalla categoria protezione alla categoria Governance

Ora puoi accedere a questo servizio dal menu di navigazione a sinistra di BlueXP selezionando *Governance > ransomware Protection*.



== 9 gennaio 2023



=== È stato aggiunto il supporto per ricevere avvisi di protezione ransomware BlueXP tramite e-mail e nel Centro notifiche

La protezione ransomware BlueXP è stata integrata nel servizio di notifica BlueXP. È possibile visualizzare le notifiche di protezione ransomware di BlueXP facendo clic sulla campana di notifica nella barra dei menu di BlueXP. È inoltre possibile configurare BlueXP per inviare notifiche via email come avvisi, in modo da essere informati di importanti attività del sistema anche quando non si è connessi al sistema. L'e-mail può essere inviata a tutti i destinatari che devono essere a conoscenza degli avvisi ransomware. https://docs.netapp.com/us-en/cloud-manager-ransomware/task-monitor-ransomware-alerts.html["Scopri come"].



== 11 dicembre 2022



=== Nuove azioni consigliate sono state aggiunte al pannello ransomware Protection Score (punteggio protezione ransomware)

Vengono ora visualizzate due nuove azioni consigliate per i seguenti problemi di protezione ransomware riscontrati nei sistemi storage:

* _Riduci i permessi per gli elementi sensibili a X con permessi ampi_ - nelle origini dati sono stati trovati file sensibili con permessi aperti
* _Patch X CVE aperte in Y origini dati_ - i CVE senza patch sono stati trovati nei sistemi ONTAP


È possibile selezionare queste azioni nell'interfaccia utente e seguire il flusso di lavoro per risolvere i problemi sottostanti. https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#list-of-recommended-actions["Consulta l'elenco di tutte le azioni consigliate"].



== 13 novembre 2022



=== Nuovi pannelli per visualizzare il punteggio complessivo di protezione ransomware e le azioni consigliate

Il pannello _ransomware Protection Score_ mostra il punteggio complessivo e le aree di cybersicurezza in cui esistono potenziali problemi. Il pannello _Recommended Actions_ elenca le potenziali azioni che puoi intraprendere per migliorare la tua resilienza a un attacco ransomware e fornisce un link per indagare sui problemi in modo da poter applicare le azioni laddove necessario. Questi due nuovi pannelli lavorano insieme per identificare la resilienza dei dati a un attacco ransomware e le azioni da eseguire per migliorare il tuo punteggio. https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#ransomware-protection-score-and-recommended-actions["Scopri di più qui"^].



== 6 settembre 2022



=== Nuovo pannello per visualizzare gli incidenti ransomware rilevati sui cluster

Il pannello _ransomware Incidents_ mostra gli attacchi ransomware che si sono verificati sui sistemi. Il supporto attuale è per i cluster ONTAP on-premise che eseguono la protezione ransomware autonoma (ARP). ARP utilizza l'analisi dei carichi di lavoro in ambienti NAS (NFS e SMB) per rilevare e avvisare in modo proattivo in caso di attività anomale che potrebbero indicare un attacco ransomware. https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#ransomware-incidents-detected-on-your-systems["Scopri di più qui"^].



== 7 agosto 2022



=== Nuovo pannello per mostrare le vulnerabilità di sicurezza dei cluster

Il pannello _vulnerabilità del sistema di storage_ mostra il numero totale di vulnerabilità di sicurezza alte, medie e basse rilevate dal tool di consulenza digitale BlueXP su ciascuno dei cluster ONTAP. Le vulnerabilità elevate devono essere immediatamente considerate per assicurarsi che i sistemi non siano aperti per gli attacchi. https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#storage-system-vulnerabilities["Fai clic qui per ulteriori informazioni"^].



=== Nuovo pannello per visualizzare i file digitalizzati immutabili

Il pannello _critical data immutability_ mostra il numero di elementi negli ambienti di lavoro protetti da modifiche ed eliminazioni sullo storage WORM grazie alla tecnologia ONTAP SnapLock. Ciò consente di visualizzare la quantità di dati che contiene una copia immutabile, in modo da poter comprendere meglio i piani di backup e ripristino rispetto al ransomware. https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#data-in-your-volumes-that-are-being-protected-using-snaplock["Fai clic qui per ulteriori informazioni"^].



== 12 giugno 2022



=== Lo stato di auditing del file system NAS viene ora monitorato per le VM di storage ONTAP

Viene aggiunto un avviso alla _Cyber Resilience Map_ se meno del 40% delle VM di storage nell'ambiente di lavoro ha attivato il controllo del file system. È possibile visualizzare il numero esatto di SVM che non tengono traccia e registrano eventi SMB e NFS in un log di audit nel pannello _rafforzare l'ambiente ONTAP_. Quindi, è possibile decidere se attivare il controllo su tali SVM.



=== Gli avvisi vengono visualizzati quando l'anti-ransomware on-box non è attivo per i volumi

Queste informazioni erano state segnalate per i sistemi ONTAP on-premise nel pannello _protezione avanzata degli ambienti ONTAP_, Ma ora viene visualizzato un avviso nella _mappa di resilienza Cyber_ quando la funzione anti-ransomware on-box è attivata in meno del 40% dei volumi, in modo da poter visualizzare queste informazioni nella dashboard.



=== I sistemi FSX per ONTAP vengono ora monitorati per l'attivazione delle snapshot dei volumi

Il pannello _protezione avanzata degli ambienti ONTAP_ fornisce ora lo stato delle copie Snapshot per i volumi sul sistema FSX per ONTAP. Quando meno del 40% dei volumi viene protetto da snapshot, viene visualizzato un avviso nella _Cyber Resilience Map_.



== 11 maggio 2022



=== Nuovo pannello per tenere traccia della protezione avanzata degli ambienti ONTAP

Un nuovo pannello _rafforzare gli ambienti ONTAP_ fornisce lo stato di alcune impostazioni nei sistemi ONTAP che monitorano la sicurezza dell'implementazione in base a. https://www.netapp.com/pdf.html?item=/media/10674-tr4569.pdf["Guida al rafforzamento della sicurezza di NetApp per sistemi ONTAP"^] e a. https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Funzione anti-ransomware di ONTAP"^] che rileva e avvisa in modo proattivo in caso di attività anomale.

Puoi rivedere i consigli e decidere come affrontare i potenziali problemi. È possibile seguire la procedura per modificare le impostazioni dei cluster, rinviare le modifiche a un'altra volta o ignorare il suggerimento. https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#status-of-ontap-systems-hardening["Fai clic qui per ulteriori informazioni"].



=== Nuovo pannello per mostrare come vengono protette le diverse categorie di dati utilizzando il backup e ripristino BlueXP

Questo nuovo pannello _Backup Status_ mostra il backup completo delle categorie di dati più importanti nel caso in cui sia necessario eseguire il ripristino a causa di un attacco ransomware. Questi dati sono una rappresentazione visiva del numero di elementi di una categoria specifica in un ambiente di cui viene eseguito il backup con il ripristino di BlueXP. https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#backup-status-of-your-critical-business-data["Fai clic qui per ulteriori informazioni"].
