= Supporto del carico di lavoro SAN
:allow-uri-read: 




=== Supporto del carico di lavoro SAN

Questa versione include il supporto per i carichi di lavoro SAN nella BlueXP ransomware protection. Ora è possibile proteggere i carichi di lavoro SAN oltre ai carichi di lavoro NFS e CIFS.

Per ulteriori informazioni, fare riferimento a link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-prerequisites.html["Prerequisiti della protezione dal ransomware di BlueXP"].



=== Protezione migliorata del carico di lavoro

Questa versione include un flusso di lavoro migliorato per la protezione dei carichi di lavoro con o senza protezione dei dati. Se si utilizzano altri strumenti di protezione dei dati NetApp , come SnapCenter o BlueXP backup and recovery , per snapshot o backup, la BlueXP ransomware protection li rileva e consente di mantenere le policy che li gestiscono. Con questa versione, è possibile sostituire tali policy con le policy BlueXP ransomware protection oppure continuare a utilizzare le policy esistenti.

Per ulteriori informazioni, fare riferimento alla https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html["Proteggere i carichi di lavoro"].



=== Notifiche via email

Se la BlueXP ransomware protection rileva un possibile attacco, viene visualizzata una notifica nelle Notifiche BlueXP e viene inviata un'e-mail all'indirizzo email configurato. Il servizio avvia immediatamente anche uno snapshot.

A questo punto dovresti visualizzare l'e-mail, che elenca la gravità e le risorse interessate, e dare un'occhiata al potenziale rischio nella scheda *Avvisi* BlueXP ransomware protection .

Se hai configurato una gestione della sicurezza e degli eventi (SIEM) nella BlueXP ransomware protection, il servizio invia i dettagli dell'avviso al tuo sistema SIEM.

Per ulteriori informazioni, fare riferimento alla https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Gestisci gli avvisi di ransomware rilevati"].
